print(66)
print(12.23)
a=66
print("黑马程序员")
#整型int
#字符串类型string
#浮点类型float
#type(被查看数据名）查看数据类型
int_type=type(a)
print(int_type)
#任何数据可以转为字符串,str()
num_str=str(888)
print(type(num_str),num_str)
#字符串转为数字,int(),想要字符串转为数字，必须字符串都是数字
str_num=int("123")
print(type(str_num),str_num)
#字符串和整数转为浮点型,float()
str_fl=float("12.1")
num_fl=12
print(type(str_fl),str_fl)
